### ISSUE TITLE
check necessary package

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#112]
everythign that is in composer.json is necessary ?

**Comment by bidi47** [comment]
need to discuss the uncertain list

UNCERTAIN - not used explicitly
dotkernel/dot-session
laminas/laminas-dependency-plugin

NOT REQUIRED - removed from root json
brick/math - required by ramsey/uuid-doctrine via ramsey/uuid
doctrine/migrations - required by roave/psr-container-doctrine

REQUIRED
doctrine/doctrine-module
dotkernel/dot-authorization
dotkernel/dot-annotated-services
dotkernel/dot-authorization
dotkernel/dot-errorhandler
dotkernel/dot-event
dotkernel/dot-flashmessenger
dotkernel/dot-form
dotkernel/dot-helpers - not used explicitly, but required by dot-navigation
dotkernel/dot-log
dotkernel/dot-mail
dotkernel/dot-navigation - not used explicitly, but required by dotkernel/dot-twigrenderer (require-dev), dotkernel/dot-helpers
dotkernel/dot-twigrenderer
laminas/laminas-authentication
laminas/laminas-component-installer
laminas/laminas-config-aggregator
laminas/laminas-diactoros
laminas/laminas-form
laminas/laminas-i18n
laminas/laminas-servicemanager
laminas/laminas-stdlib
mezzio/mezzio
mezzio/mezzio-authorization-rbac
mezzio/mezzio-fastroute
mezzio/mezzio-helpers
mezzio/mezzio-twigrenderer
ramsey/uuid-doctrine
roave/psr-container-doctrine
robmorgan/phinx - migrations
tuupola/cors-middleware
twig/extensions - used for translations

**Comment by arhimede** [comment]
can you confirm the list of REQUIRED dot- packages are the ones from here ?
https://github.com/dotkernel/dotkernel/blob/master/checklist-v3-packages.md

**Comment by bidi47** [comment]
confirmed, it's the same list

**Comment by arhimede** [comment]
then you can close the ticket :-)

**Comment by bidi47** [comment]
roger that

we clarified that these packages are required
dotkernel/dot-session
laminas/laminas-dependency-plugin

i'll submit a pull request with the updated list
