### ISSUE TITLE
check packages in homepage

### ISSUE THREAD

**Issue by bidi47** [dotkernel/frontend#113]
there are references to the older packages in the homepage footer 
they need to be updated/removed

**Comment by bidi47** [comment]
removed packages are listed below

dot-authentication
dot-authentication-service
dot-authentication-web
dot-user

dot-rbac
dot-rbac-guard

dot-controller-plugin-authentication
dot-controller-plugin-authorization
dot-controller-plugin-flashmessenger
dot-controller-plugin-forms
dot-controller-plugin-mail
dot-controller-plugin-session

dot-filter
dot-validator
dot-inputfilter
dot-hydrator

dot-mapper

dot-paginator

dot-cache

**Comment by arhimede** [comment]
we are doing some major changes 
add back dot_controller 
and probably other packages too

**Comment by bidi47** [comment]
related to https://github.com/dotkernel/frontend/issues/118
i'll update the readme and homepage when update with dot-controller is merged into 3.0
