### ISSUE TITLE
test dot=controller integration

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#119]
starting from branch https://github.com/dotkernel/frontend/tree/issue-118
please test if is working fine 

check for typos

**Comment by Calin23** [comment]
Testing Status for [issue-118:](https://github.com/dotkernel/frontend/tree/issue-118)
- I don't know if is a problem from my side when I run the command "composer install" all packages are installed except "dotkernel/dot-controller" so this will return "Class 'Dot\Controller\AbstractActionController' not found" 
- runing "composer install" second time will do nothing it will return "Nothing to install or update
"
- I tested the installation three times same problem
- if I run "composer update" it will install the missing package
- dot-controller integration is working tested

Tested on:
- macOS Catalina
- Version 10.15.4

**Comment by bidi47** [comment]
> 
> 
> Testing Status for [issue-118:](https://github.com/dotkernel/frontend/tree/issue-118)
> 
>     * I don't know if is a problem from my side when I run the command "composer install" all packages are installed except "dotkernel/dot-controller" so this will return "Class 'Dot\Controller\AbstractActionController' not found"
> 
>     * runing "composer install" second time will do nothing it will return "Nothing to install or update
>       "
> 
>     * I tested the installation three times same problem
> 
>     * if I run "composer update" it will install the missing package
> 
>     * dot-controller integration is working tested
> 
> 
> Tested on:
> 
>     * macOS Catalina
> 
>     * Version 10.15.4

make sure you are on branch 'issue-118' 
if you simply use git clone, the installation defaults to branch '3.0' where dot-controller isn't added yet

**Comment by Calin23** [comment]
Thanks for the hint @bidi47 but the problem for installing the missing package was because of the **composer.lock** file , it was removed so it is not an issue anymore for installing the packages.

**Comment by bidi47** [comment]
ok, i'll close this issue for now
