### ISSUE TITLE
customise email templates

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#132]
Please customize all email templates sent by the system 
In order to be generic enough 

test it on v3.dotkernel.net

**Comment by arhimede** [comment]
@alinaclaudia please create templates for emails, using generic html

**Comment by arhimede** [comment]
@bidi47  and add in the documentation whre are those templates

**Comment by bidi47** [comment]
these are the email templates provided on a fresh installation, all in the User module
activate.html.twig
reset-password-requested.html.twig
reset-password-completed.html.twig

the update is included in this pull request
https://github.com/dotkernel/frontend/pull/165
