### ISSUE TITLE
Remove pagination class from common

### ISSUE THREAD

**Issue by roli85** [dotkernel/frontend#175]
Pagination class is used to get offset and limit, but the values are hardcoded. It should be removed

**Comment by arhimede** [comment]
In the file /src/App/src/Common/Pagination.php 
is that class Pagination used soemwhere else ?

@roli85  please confirm if you use it

**Comment by arhimede** [comment]
1. the class is used here and there , so wil stay 

2. Knowing that the values are hardcoded, is too complicated to move that values in some config file 

So i am closing the ticket now @roli85
