### ISSUE TITLE
Implement rememberMe 

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#191]
implement rememberMe function (cookie related)

**Comment by arhimede** [comment]
@SergiuBota1 we need instructions about how to implement this 
as i am getting error 500 
Service with name \"Frontend\\App\\Middleware\\RememberMeMiddleware\" could not be created.

**Comment by arhimede** [comment]
@SergiuBota1 
1. rename the table in " user_remember_me"
2. remove from local.php.dist the values:           'code_set' => 'UTF-8',   'domain' => 'messages',
            'base_dir' => getcwd() . '/data/rememberMe',

**Comment by arhimede** [comment]
@SergiuBota1 
in "remember_user" table, in the column deviceModel you are storing userAgent actually
you should rename the column

**Comment by SergiuBota1** [comment]
#274
