### ISSUE TITLE
error_log in src/Plugin/src/Factory/PluginManagerAwareInitializer.php

### ISSUE THREAD

**Issue by roli85** [dotkernel/frontend#202]
there is a useless error_log in this file, on line 29, which will print out the class name in the built in server console
but also will spam the apache error log with a huge text containing all the class names, on every refresh:

<img width="1012" alt="Screenshot 2020-09-25 at 15 52 05" src="https://user-images.githubusercontent.com/48314447/94431451-fc573900-019d-11eb-9eb3-66dc41596764.png">

line 29 needs removal

**Comment by arhimede** [comment]
@roli85  you can create a pull request for this one

**Comment by arhimede** [comment]
closed in https://github.com/dotkernel/frontend/pull/206
