### ISSUE TITLE
Binary UUID in session 

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#210]
remove the binary UUID from session 
eventually  convert to-string the binary value

**Comment by arhimede** [comment]
Frontend\User\Entity\UserRole
Ramsey\Uuid\Rfc4122\UuidV1":16:{êò£Ù•åª—ˆ

**Comment by arhimede** [comment]
error message in logs below:
 Got error 'PHP message: PHP Warning:  session_start(): Failed to decode session object. Session has been destroyed in /var/www/vhosts/example.com/httpdocs/vendor/laminas/laminas-session/src/SessionManager.php on line 139', referer:

**Comment by Calin23** [comment]
After a bit of research, the `getUuid()` method in `UuidAwareTrait.php` will return an instance that depends entirely on the version of the `ramsey/uuid` package installed.

Here you can se the Return types for Uuid static methods based on version [Ramsey Static Methods](https://uuid.ramsey.dev/en/latest/upgrading/3-to-4.html#uuid-static-methods).

So we can specify the `ramsey/uuid` in `composer.json` not greater than `3.9`, and we will get an instance of de `Uuid` without binary fields, but we will be limited to the current version.

Or we can use the latest version of `ramsey/uuid` but with the idea of not saving `Rfc4122\UuidV1` instance in session.

I changed the `roles` value so now will no more return a `Rfc4122\UuidV1` instance in session, [d316e05](https://github.com/dotkernel/frontend/commit/d316e0516e3424355311d1bee7638c6989e41b16).

**Comment by arhimede** [comment]
closed in #223
