### ISSUE TITLE
Requirements missing

### ISSUE THREAD

**Issue by adrianmester** [dotkernel/frontend#23]
Requirements should be added to the readme file.

For example, it should specify that PHP7.1 is the minimum supported version.

In addition to that, I also had to install the following packages:
- xml
- mbstring

On ubuntu, the following steps should install everything needed, not sure about other OSes:

```bash
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get install php7.1 php7.1-xml php7.1-mbstring
```

**Comment by n3vrax** [comment]
I agree documentation is poorly written
For now, readme file was updated to include the main requirements

Installation is also problematic, it isn't actually an 'install', it is rather a git clone(see `composer create-project`)

Hope it will change in the future, by writing complete documentation, and customize the composer installation with scripts

Anyway, documentation should be moved to a /docs folder, where we can detail more, and keep the readme file short
