### ISSUE TITLE
ramsey-uuid 4.2 crash the uuid login

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#236]
if ramsey/uuid >= 4.2.1 the login crashes 
( requested by ramsey/uuid-doctrine 1.7 ) 

need to be removed " abstract repository "

**Comment by alexmerlin** [comment]
Using the below packages, login did not crash:

- ramsey/uuid:4.2.1
- ramsey/uuid-doctrine:1.7.0

Need more details on the issue.

**Comment by bidi47** [comment]
@arhimede is this still a issue?
if not, we can close the ticket

**Comment by arhimede** [comment]
is not an issue anymore
