### ISSUE TITLE
integrate debug toolbar ?

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#246]
https://github.com/php-middleware/phpdebugbar

https://docs.mezzio.dev/mezzio/v3/cookbook/debug-toolbars/

How to integrate phpdebugbar or any other debug tools in dotkernel ?

as from time to time we need to know

**Comment by arhimede** [comment]
or maybe use the good ol' xhprof  ?

http://pecl.php.net/package/xhprof

**Comment by bidi47** [comment]
@arhimede let's see what to do about the debugging
we haven't reached a decision on it

**Comment by arhimede** [comment]
@alexmerlin  please do a pull request to the branch 4.0
