### ISSUE TITLE
allow-plugins dotkernel

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#247]
https://getcomposer.org/doc/06-config.md#allow-plugins

let's add in the composer.json , allow-plugins section 

"my-organization/*": true,
"dotkernel/*": true,

**Comment by alexmerlin** [comment]
I've already prepared a patch that creates the `allow-plugins` object and adds the following packages to it:
* laminas/laminas-dependency-plugin
* laminas/laminas-component-installer
* composer/package-versions-deprecated
* dotkernel/*
