### ISSUE TITLE
 laminas form

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#249]
1. check if the package laminas/laminas-form is required 
2.  if can be removed from composer, remove it 
3. make a new release with the updated composer.json file 
4. trebe sa dam la baietii noul composer sa stie gen

**Comment by bidi47** [comment]
laminas form is removed
checking other laminas, mezzio packages that can be removed from the root composer.json

**Comment by bidi47** [comment]
after laminas-form upgrade, getting error below on php ^7.4
the older version (2.17) didn't have Laminas\Form\FormAbstractServiceFactory declared as final, so now our dot-form can't extend it

Fatal error: Class Dot\Form\Factory\FormAbstractServiceFactory may not inherit from final class (Laminas\Form\FormAbstractServiceFactory) in \frontend\vendor\dotkernel\dot-form\src\Factory\FormAbstractServiceFactory.php on line 20

**Comment by arhimede** [comment]
@alexmerlin

**Comment by alexmerlin** [comment]
Quick and dirty solution - as `Dot\Form\Factory\FormAbstractServiceFactory` already implements the same methods as `Laminas\Form\FormAbstractServiceFactory`:
* adapt our factory by making sure each method does the same thing as theirs
* remove from our factory the `extends \Laminas\Form\FormAbstractServiceFactory` part
* add to our factory `implements AbstractFactoryInterface` (with `use Laminas\ServiceManager\Factory\AbstractFactoryInterface;`)

**NOTE**:
This decouples our class from theirs - which means that if they add some functionality into their factory, we need to update ours.

**Comment by bidi47** [comment]
added update for existing open pull request
https://github.com/dotkernel/frontend/pull/251

**Comment by arhimede** [comment]
"message":"Argument 1 passed to Laminas\\Form\\Element\\Checkbox::setUncheckedValue() must be of the type string, bool given, called in /var/www/vhosts/v3.dotkernel.net/httpdocs/vendor/laminas/laminas-form/src/Element/Checkbox.php on line 52","extra":{"\u0000*\u0000message":"Argument 1 passed to Laminas\\Form\\Element\\Checkbox::setUncheckedValue() must be of the type string, bool given, called in /var/www/vhosts/v3.dotkernel.net/httpdocs/vendor/laminas/laminas-form/src/Element/Checkbox.php on line 52"

**Comment by bidi47** [comment]
unlike in v2, laminas-form v3.1.1 has strict data types for checkboxes
the delete account form is updated
