### ISSUE TITLE
update composer

### ISSUE THREAD

**Issue by bidi47** [dotkernel/frontend#254]
remove packages from root _composer.json_ if they are are already required by other packages

**Comment by bidi47** [comment]
removed packages
dotkernel/dot-event - required by dotkernel/dot-mail
dotkernel/dot-helpers - required by dotkernel/dot-navigation
dotkernel/dot-log - required by dotkernel/dot-errorhandler
dotkernel/dot-rbac - required by dotkernel/dot-rbac-guard
mezzio/mezzio - required by dotkernel/dot-errorhandler

**Comment by arhimede** [comment]
fix dot-errorhandler 
and add back here mexxio/mezzio

**Comment by bidi47** [comment]
dot-errorhandler is updated - we should review and make a new release
added mezzio/mezzio in https://github.com/dotkernel/frontend/pull/257
