### ISSUE TITLE
Fresh installation broken

### ISSUE THREAD

**Issue by alexmerlin** [dotkernel/frontend#284]
Upon running a fresh installation of the project, accessing the home page from a browser throws the following error:

> Service with name "dot-mail.service.default" could not be created. Reason: cannot connect to host; error = stream_socket_client(): Unable to connect to tcp://:143 (No connection could be made because the target machine actively refused it) (errno = 0 )

Tested on:
* OS: Windows 11, Ubuntu 20.04 and MacOS Mojave
* PHP: versions 7.4 and 8.1

**Comment by arhimede** [comment]
1. Do you have sendmail installed on any of your setup ?
2. Why on Earth is trying to connect to mail server from the very begining ?

**Comment by alexmerlin** [comment]
Under Xampp (PHP 8.1) I'm almost sure I did not install sendmail - but that's not relevant. It shouldn't even try to connect when I open the homepage. Didn't have time yet to dig deeper on why it even tries to connect to a mail server.

**Comment by arhimede** [comment]
![image](https://user-images.githubusercontent.com/22009710/186378295-9d5b2fc6-232b-4674-b678-b09d56c40afd.png)

**Comment by arhimede** [comment]
![image (1)](https://user-images.githubusercontent.com/22009710/186378372-ea75abe8-ad95-4f35-8394-b6d63d93e30a.png)

**Comment by bidi47** [comment]
fixed in pulls https://github.com/dotkernel/dot-mail/pull/33, https://github.com/dotkernel/dot-mail/pull/36, https://github.com/dotkernel/dot-mail/pull/38, https://github.com/dotkernel/dot-mail/pull/41
