### ISSUE TITLE
split the mail config file based on Transport

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#285]
mail.local.php.dist
in frontend, admin and api 

also the global file https://github.com/dotkernel/dot-mail/blob/4.0/mail.global.php.dist

split in 2 separate dist files:
1. master: define the Transport and the message options
2. a smtp  dist file with specific to smtp  option , IF any

**Comment by arhimede** [comment]
also remove the FIle and Memory options, are not used

**Comment by arhimede** [comment]
linked to the issue #320

**Comment by alexmerlin** [comment]
@arhimede Now that we copy the main config file on compoer install/update, I guess this is no longer necessary?
