### ISSUE TITLE
dot-mail correct requirement

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#295]
"dotkernel/dot-mail": "~3.4 || ~4.0",

based on the PHP version

**Comment by bidi47** [comment]
updated in 
https://github.com/dotkernel/frontend/pull/297 - pending review
https://github.com/dotkernel/api/pull/132 - pending review
https://github.com/dotkernel/admin/pull/125

**Comment by bidi47** [comment]
all pulls are approved and closed
