### ISSUE TITLE
update javascript packages

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#298]
please be sure that is compiling with node 16

**Comment by arhimede** [comment]
@mada27 bump

**Comment by mada27** [comment]
I compiled without problems with node version: 16.15.1
and npm: 8.19.2

**Comment by mada27** [comment]
Otherwise, I also tried with a previous version of npm: 8.7.0
The compilation works without problems

**Comment by SergiuBota1** [comment]
#302
