### ISSUE TITLE
require-dev updated

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#301]
"require-dev": {
        "laminas/laminas-development-mode": "^3.8.0",
        "mezzio/mezzio-tooling": "^2.5.0",
        "phpunit/phpunit": "^9.5.21",
        "roave/security-advisories": "dev-master",
        "squizlabs/php_codesniffer": "^3.7.1",
        "filp/whoops": "^2.14.5"

Check everything if:
1. is worth to be there  ( are used somewhere  ?) 
2. update to the latest versions

**Comment by arhimede** [comment]
only for branch 4.0

**Comment by SergiuBota1** [comment]
Solved in #325
