### ISSUE TITLE
New release of V3

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#309]
- phinx replace with doctinre migration 
- psalm version 7.4

**Comment by marioradu05** [comment]
Phinx was replaced with dotkernel/dot-data-fixtures in this PR : https://github.com/dotkernel/frontend/pull/287.
Psalm was implemented in this PR : https://github.com/dotkernel/frontend/pull/303  - 4.0 branch.
This PR https://github.com/dotkernel/frontend/pull/305 introduced psalm into the 3.0 branch.
We only need to create a new release for the 3.0 branch.

**Comment by arhimede** [comment]
release 3.3.0
