### ISSUE TITLE
Initial  release of V4

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#310]
- psalm 8.1
- composer 8.1 and 8.2

**Comment by arhimede** [comment]
+ modify readme.md to be in sync ( badges)

**Comment by SergiuBota1** [comment]
Solved in #322

**Comment by marioradu05** [comment]
@SergiuBota1  we didn't made a new release for v4 so I'm reopening this issue.

**Comment by marioradu05** [comment]
Created a new 4.0.0 release. 
https://github.com/dotkernel/frontend/releases/tag/4.0.0
