### ISSUE TITLE
DK Translator Issue

### ISSUE THREAD

**Issue by pinclau** [dotkernel/frontend#311]
If a cookie "dk30Translator" is set with a key other than "en" or "dk" basically another key from the config file. it returns: 
ErrorException (E_WARNING)
Undefined array key "{key}"

App/src/Middleware/TranslatorMiddleware.php74

It needs to verify if it exists in the config, not accessed directly.

**Comment by arhimede** [comment]
@SergiuBota1  pelase test it and confirm is fixed

**Comment by SergiuBota1** [comment]
I tested it and it works as it should
