### ISSUE TITLE
Psalm issue on all InputFilters

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#335]
Error: src/User/src/InputFilter/UserDetailInputFilter.php:42:20: InvalidArgument: Argument 1 of Frontend\User\InputFilter\UserDetailInputFilter::add expects Laminas\InputFilter\InputFilterInterface|Laminas\InputFilter\InputInterface|Traversable|type-alias(Laminas\InputFilter\InputFilterInterface::InputSpecification), but array{filters: array{array{name: "StringTrim"}}, name: "lastName", required: true, validators: array{array{break_chain_on_failure: true, name: "NotEmpty", options: array{message: "<b>Last Name</b> is required and cannot be empty"}}}} provided (see https://psalm.dev/004)

**Comment by alexmerlin** [comment]
Fixed in #344
