### ISSUE TITLE
Unused field 'subject' in ContactForm

### ISSUE THREAD

**Issue by alexmerlin** [dotkernel/frontend#341]
When the contact message is being sent, the subject is hardcoded instead of using the value provided by the ContactForm's data.
Also, the field `subject` is initialized in src/Contact/src/InputFilter/ContactInputFilter.php but not displayed in the form itself.
Should we then eliminate the field `subject` form the ContactForm?

**Comment by arhimede** [comment]
related somehow to ticket #134

**Comment by alexmerlin** [comment]
Fixed in #344
