### ISSUE TITLE
ramsey/uuid issue at upgrade to 2.0 

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#358]
related to this issue 
https://github.com/ramsey/uuid-doctrine/issues/200

so we should stay for the moment at version 1.8.x

**Comment by arhimede** [comment]
related issue 
https://github.com/ramsey/uuid-doctrine/issues/164

**Comment by bidi47** [comment]
just saw this
should i undo the upgrade to "ramsey/uuid-doctrine": "^2.0.0" in https://github.com/dotkernel/frontend/pull/417/files?
