### ISSUE TITLE
Investigate root .gitignore

### ISSUE THREAD

**Issue by bidi47** [dotkernel/frontend#430]
Currently .gitignore has a line for phpunit.xml, so it wasn't pushed in a recent deploy and the phpunit tests failed to run.
Investigate if .gitignore needs to be updated.

**Comment by arhimede** [comment]
also add on .gitignore the project specific files:
config/autoload/local.php
                          mail.local.php
                          debugbar.local.php
                          development.local.php

**Comment by arhimede** [comment]
and the folders:
  data/cache

**Comment by alexmerlin** [comment]
> also add on .gitignore the project specific files:
> config/autoload/local.php
> mail.local.php
> debugbar.local.php
> development.local.php

`*.local` files are already ignored in [this](https://github.com/dotkernel/frontend/blob/4.0/config/autoload/.gitignore) file

**Comment by alexmerlin** [comment]
> and the folders: data/cache

cache directory is already ignored in [this](https://github.com/dotkernel/frontend/blob/4.0/data/.gitignore) file

**Comment by bidi47** [comment]
resolved in https://github.com/dotkernel/frontend/pull/435
