### ISSUE TITLE
remove Translation feature

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#445]
but let's prepare it as a separate package

**Comment by arhimede** [comment]
check if we can use laminas-i8n instead
and how 

https://github.com/laminas/laminas-i18n

**Comment by bidi47** [comment]
created PR for review https://github.com/dotkernel/frontend/pull/468
and article for setting up the translation feature https://git.apidemia.net/websites/dotkernel.org/-/wikis/Translation-feature
