### ISSUE TITLE
composer.json review

### ISSUE THREAD

**Issue by bidi47** [dotkernel/frontend#458]
we have dotkernel/dot-session which requires laminas/laminas-session
composer.json contains both dotkernel/dot-session and laminas/laminas-session
can laminas/laminas-session be removed from composer.json?

**Comment by alexmerlin** [comment]
You can see when that specific line was introduced by going [here](https://github.com/dotkernel/frontend/blame/5.0/composer.json#L67) and hovering on the commit message.

The line `"laminas/laminas-session": "^2.21.0",` was added to the requirements a couple of days ago when we implemented CSRF in both DK Admin and Frontend. This feature needs the new [CSRF](https://github.com/laminas/laminas-session/blob/2.21.x/src/Validator/Csrf.php) validator, which was introduced in version `2.21.x`.

Once we bump laminas-session to `^2.21` in dot-session, we can remove this requirement from both projects. Here's the task list:

- [ ] https://github.com/dotkernel/dot-session/issues/39
- [ ] https://github.com/dotkernel/frontend/issues/459
- [ ] https://github.com/dotkernel/admin/issues/273

**Comment by bidi47** [comment]
the topic is resolved in the issues you mentioned
i'll close this ticket
