### ISSUE TITLE
Checks for incomplete database

### ISSUE THREAD

**Issue by bidi47** [dotkernel/frontend#47]
I just installed DK3 from scratch and got some errors in phpmyadmin when I tried to import data/frontend.sql into the database. Strangely, the site still works, I logged in, but the account icon on the top-right isn't displaying any more and I'm not redirected to the account page. I had to log out manually and rerun the queries between lock and unlock.

I'm thinking there should be a check at some point in the code, to verify the integrity of the database out-of-the-box. An error in the login page would really help figure out the issue.

**Comment by n3vrax** [comment]
DB is complete, could be something related to phpmyadmin?

Try importing the file through command line instead, by running this command, and let me know if you encounter the same errors

```bash
$ mysql -u username -p dbname < /path/to/sql/file.sql
```

Anyway, the next version of frontend will use db migrations instead, more reliable than passing a file around

**Comment by arhimede** [comment]
We need to investigate this in detail and try to reproduce it . 
I will assign this to Radu
