### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by dotcostin** [dotkernel/frontend#53]
Problems with frontend installation. Related to packages versions.

Problem 1
    - dotkernel/dot-event v0.2.1 requires zendframework/zend-eventmanager ^3.2 -> satisfiable by zendframework/zend-eventmanager[3.2.0, 3.2.1, 3.3.x-dev, 3.2.x-dev] but these conflict with your requirements or minimum-stability.
    - dotkernel/dot-mail 1.0.0 requires dotkernel/dot-event ^0.2.1 -> satisfiable by dotkernel/dot-event[v0.2.1].
    - Installation request for dotkernel/dot-mail 1.0 -> satisfiable by dotkernel/dot-mail[1.0.0].

**Comment by gabidj** [comment]
This issue was resolved in [v1.0.1](https://github.com/dotkernel/frontend/releases/tag/v1.0.1)

Closing issue.
Thank you for your feedback.
