### ISSUE TITLE
"zendframework/zend-stratigility": "3.0"

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#69]
why the version  of "zendframework/zend-stratigility": "3.0", is hardcoded to 3.0 ?

it may be a good idea to use the latest current, 3.2.0 ?

https://github.com/zendframework/zend-stratigility/releases/tag/3.2.0

**Comment by alexmerlin** [comment]
Not sure why the requirements were for exactly version 3.0
For now I changed the dependency to the latest version (3.2.0) and checked across the system to make sure that each page works as intended.
