### ISSUE TITLE
phinx package update

### ISSUE THREAD

**Issue by bidi47** [dotkernel/frontend#83]
the phinx package has this setup in composer.json
`"robmorgan/phinx": "^0.11",`
so it installs version 0.11.6

the latest version is 0.12.1, but a manual update has conflicts with cakephp packages

consider doctrine alternative

**Comment by d3aq** [comment]
Please try again, because I tested with package updated to 12.1
`"robmorgan/phinx": "^0.12"`
and everything works fine, no conflicts between packages.

**Comment by arhimede** [comment]
hmm, i just tested with:
"robmorgan/phinx": "^0.12",

on Centos 7 Plesk and seem to be fine
@bidi47  can you provide a test case, how to reproduce the issue ?

**Comment by bidi47** [comment]
you're right
updating with `composer update robmorgan/phinx` ignored the dependencies on my end
a simple `composer update` didn't complain and i'll push this to be merged into branch 3.0
