### ISSUE TITLE
check the javascript libraries

### ISSUE THREAD

**Issue by arhimede** [dotkernel/frontend#97]
https://github.com/dotkernel/frontend/blob/3.0/package.json

1. if there are too many libraries included , remove the uncessary ones 

2. the remaining ones, if need to be updated , please do , to have the lastest

**Comment by arhimede** [comment]
@alinaclaudia  can you confirm that all javascript libraries included are necessary ?

in order to close this ticket

**Comment by alinaclaudia** [comment]
all the javascript libraries are necessary
